platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

workspace 'MVCChat'

def base_pods
    pod 'SwiftLint'
    pod 'R.swift'
    pod 'Constraint'
end

target 'MVCChat' do
    project 'MVCChat.xcodeproj'
    base_pods
end
